apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base/clusterissuer-letsencrypt.yaml
patches:
  - path: external-dns-patch.yaml
  - path: clusterissuer-patch.yaml
